/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';
import { LiWEResponse, sendParametersError, sendResponse } from '../../liwe/response';

import {
	// endpoints function
	delete_order_admin_del, delete_order_admin_del_real, delete_order_item_del, get_order_admin_details, get_order_admin_list,
	get_order_cart, get_order_details, get_order_get, get_order_list, patch_order_change_status,
	post_order_add, post_order_notes_add, post_order_set_delivery_address, post_order_transaction_failed, post_order_transaction_start,
	post_order_transaction_success, post_order_transaction_update,
	// functions
	order_add_product, order_db_init, order_get, order_get_by_transaction_id, order_get_full,
	order_get_open, order_payment_cancelled, order_payment_completed, order_set_status, order_transaction_start,
	order_transaction_update,
} from './methods';

import {
	Order, OrderFull, OrderFullKeys, OrderItem, OrderItemKeys,
	OrderKeys, OrderPaymentLog, OrderPaymentLogKeys, OrderPaymentStatus, OrderPaymentStatusObj,
	OrderStatus, OrderStatusObj,
} from './types';

/*=== f2c_start __header ===*/

/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - order " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "order", l ) );
	order_db_init ( liwe );

	app.get ( '/api/order/admin/list', perms( [ "order.add" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { skip, rows, ___errors } = typed_dict( req.query as any, [
			{ name: "skip", type: "number" },
			{ name: "rows", type: "number" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_order_admin_list ( req, skip, rows);
		sendResponse ( res, response );
	} );

	app.delete ( '/api/order/admin/del', perms( [ "order.add" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_order_admin_del ( req, id);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/add', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { prod_code, qnt, overwrite, ___errors } = typed_dict( req.body, [
			{ name: "prod_code", type: "string", required: true },
			{ name: "qnt", type: "number", required: true, default: 1 },
			{ name: "overwrite", type: "boolean" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_add ( req, prod_code, qnt, overwrite);
		sendResponse ( res, response );
	} );

	app.get ( '/api/order/details',  async ( req: ILRequest, res: ILResponse ) => {
		const { id, code, ___errors } = typed_dict( req.query as any, [
			{ name: "id", type: "string" },
			{ name: "code", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_order_details ( req, id, code);
		sendResponse ( res, response );
	} );

	app.get ( '/api/order/list',  async ( req: ILRequest, res: ILResponse ) => {
		const { rows, skip, ___errors } = typed_dict( req.query as any, [
			{ name: "rows", type: "number" },
			{ name: "skip", type: "number" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_order_list ( req, rows, skip);
		sendResponse ( res, response );
	} );

	app.get ( '/api/order/cart', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_order_cart ( req, );
		sendResponse ( res, response );
	} );

	app.delete ( '/api/order/item/del', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id_order, id_item, ___errors } = typed_dict( req.body, [
			{ name: "id_order", type: "string", required: true },
			{ name: "id_item", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_order_item_del ( req, id_order, id_item);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/transaction/start',  async ( req: ILRequest, res: ILResponse ) => {
		const { id_order, challenge, payment_mode, transaction_id, session_id, ___errors } = typed_dict( req.body, [
			{ name: "id_order", type: "string", required: true },
			{ name: "challenge", type: "string", required: true },
			{ name: "payment_mode", type: "string", required: true },
			{ name: "transaction_id", type: "string", required: true },
			{ name: "session_id", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_transaction_start ( req, id_order, challenge, payment_mode, transaction_id, session_id);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/transaction/update',  async ( req: ILRequest, res: ILResponse ) => {
		const { challenge, payment_mode, transaction_id, session_id, event_name, data, ___errors } = typed_dict( req.body, [
			{ name: "challenge", type: "string", required: true },
			{ name: "payment_mode", type: "string", required: true },
			{ name: "transaction_id", type: "string", required: true },
			{ name: "session_id", type: "string" },
			{ name: "event_name", type: "string" },
			{ name: "data", type: "any" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_transaction_update ( req, challenge, payment_mode, transaction_id, session_id, event_name, data);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/transaction/success',  async ( req: ILRequest, res: ILResponse ) => {
		const { challenge, transaction_id, session_id, payment_mode, ___errors } = typed_dict( req.body, [
			{ name: "challenge", type: "string", required: true },
			{ name: "transaction_id", type: "string", required: true },
			{ name: "session_id", type: "string" },
			{ name: "payment_mode", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_transaction_success ( req, challenge, transaction_id, session_id, payment_mode);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/transaction/failed',  async ( req: ILRequest, res: ILResponse ) => {
		const { challenge, transaction_id, session_id, payment_mode, ___errors } = typed_dict( req.body, [
			{ name: "challenge", type: "string", required: true },
			{ name: "transaction_id", type: "string", required: true },
			{ name: "session_id", type: "string" },
			{ name: "payment_mode", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_transaction_failed ( req, challenge, transaction_id, session_id, payment_mode);
		sendResponse ( res, response );
	} );

	app.get ( '/api/order/admin/details', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, ___errors } = typed_dict( req.query as any, [
			{ name: "id", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_order_admin_details ( req, id);
		sendResponse ( res, response );
	} );

	app.delete ( '/api/order/admin/del/real', perms( [ "order.add" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_order_admin_del_real ( req, id);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/notes/add', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { notes, id, code, ___errors } = typed_dict( req.body, [
			{ name: "notes", type: "string", required: true },
			{ name: "id", type: "string" },
			{ name: "code", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_notes_add ( req, notes, id, code);
		sendResponse ( res, response );
	} );

	app.post ( '/api/order/set/delivery/address', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, address, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "address", type: "any", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_order_set_delivery_address ( req, id, address);
		sendResponse ( res, response );
	} );

	app.get ( '/api/order/get',  async ( req: ILRequest, res: ILResponse ) => {
		const { challenge, id, code, ___errors } = typed_dict( req.query as any, [
			{ name: "challenge", type: "string", required: true },
			{ name: "id", type: "string" },
			{ name: "code", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_order_get ( req, challenge, id, code);
		sendResponse ( res, response );
	} );

	app.patch ( '/api/order/change/status',  async ( req: ILRequest, res: ILResponse ) => {
		const { id, status, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "status", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_order_change_status ( req, id, status);
		sendResponse ( res, response );
	} );

};
