/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"order.add": "User can add / modify / delete an order",
	"order.address_update": "The user can update delivery address of any order",
};

export default permissions;
